exp_name: 'opt_pose' # 'opt_pose_vis_pose2_gt_feature'
output_dir: './output'
log_dir: './log'
workers: 8
print_freq: 100
vis_freq: 1000
eval_vis_freq: 1
seed: 42

dataset:
  name: 'kubric'
  category: 'general'
  task: 'singlesequence'
  img_size: 256
  num_frame: 5
  mask_images: True
  augmentation: False

network:
  backbone: 'resnet'
  scale_rotate: 0.01 # 0.01
  scale_translate: 0.01 # 0.01
  padding_mode: 'zeros'
  rot_representation: 'quat'  # 'euler'

render:
  n_pts_per_ray: 64 #64 #100, 64
  volume_size: 1.0  # physical size in meters
  min_depth: 0.5  # rendering sample depth in meters
  max_depth: 2.0
  camera_z: 1.5
  k_size: 5

loss:
  recon_rgb: 5.0
  recon_mask: 2.0
  perceptual_img: 0.02
  regu_origin_proj: 1.0

train:
  lr: 0.0002 #0.0002 # 0.0002
  weight_decay: 0 #0.00001 #0
  schedular_step: 100
  schedular_gamma: 0.7
  end_epoch: 3000
  resume: True
  batch_size: 1 #4
  snapshot_freq: 10
  total_iteration: 200000
  use_gt_pose: False
  canonicalize: True
  accumulation_step: 1 #4

test:
  batch_size: 1
  compute_metric: True